#!/bin/sh

shopt -s extglob

stdin="$(cat)"
host="$(echo "$stdin" | grep host | cut -d "=" -f 2- | sed 's/^git\.//')"
user="$(echo "$stdin" | grep user | cut -d "=" -f 2-)"

# Strip port from host
host=${host%:+([0-9])}

# Strip "mail." or "smtp." subdomain from host
host=${host#@(mail.|smtp.)}

if [ "$1" = "get" ] && [ -n "$user" ]; then
	echo -n "password="
	pass show "$host/$user"
	exit $?
fi

exit 1
