#!/usr/bin/env bash
hc() {
    herbstclient "$@"
}

hc emit_hook reload


# ┌───────────┐
# │ variables │
# └───────────┘
# modifier key is the super key
mod=Mod4

# tag (virtual desktop) names and keys ($mod-key to go to tag)
tag_names=( {1..9} 0 )
tag_keys=( {1..9} 0 )

# default layout for all tags
hc set default_frame_layout grid

resizestep=0.02


# ┌──────────┐
# │ keybinds │
# └──────────┘
hc keyunbind --all

# spawning programs
hc keybind $mod-Shift-b spawn 	~/.config/herbstluftwm/scripts/setbackground.sh
hc keybind $mod-Return spawn 	"${TERMINAL:-kitty}"
hc keybind $mod-p spawn 		rofi -show drun
hc keybind $mod-o spawn 		qutebrowser
hc keybind $mod-Shift-p spawn 	passmenu

# changing keyboard layout
hc keybind $mod-Shift-space spawn 	xkblayout-state set +1

# vim-style command line for window switching and control
hc keybind $mod-semicolon spawn ~/.config/herbstluftwm/scripts/commandline.sh
hc keybind $mod-slash spawn 	~/.config/herbstluftwm/scripts/windowline.sh

# emoji picker
hc keybind $mod+Shift+e spawn 	rofi -show emoji -modi emoji

# dismiss notification
hc keybind $mod-d spawn		dunstctl close

# media keys
hc keybind XF86AudioPause spawn 	mpc pause
hc keybind XF86AudioPlay spawn 		mpc toggle
hc keybind XF86AudioNext spawn 		mpc next
hc keybind XF86AudioPrev spawn 		mpc prev

# volume controls
hc keybind XF86AudioRaiseVolume 	spawn ~/.config/herbstluftwm/scripts/setvolume.sh up;
hc keybind XF86AudioLowerVolume 	spawn ~/.config/herbstluftwm/scripts/setvolume.sh down;
hc keybind XF86AudioMute 			spawn ~/.config/herbstluftwm/scripts/setvolume.sh toggle;

# toggle mute on microphone - passthrough or real
hc keybind $mod-m spawn ~/.config/herbstluftwm/scripts/setmic.sh real-toggle
hc keybind $mod-n spawn ~/.config/herbstluftwm/scripts/setmic.sh virtual-toggle

# brightness controls
hc keybind XF86MonBrightnessUp 	 spawn ~/.config/herbstluftwm/scripts/setbrightness.sh up;
hc keybind XF86MonBrightnessDown spawn ~/.config/herbstluftwm/scripts/setbrightness.sh down;

# screenshots
hc keybind Print 		spawn \
	~/.config/herbstluftwm/scripts/screenshot.sh --area
hc keybind Shift-Print 	spawn \
	~/.config/herbstluftwm/scripts/screenshot.sh --screen

# window control
hc keybind $mod-Shift-q quit
hc keybind $mod-q 		close_or_remove

# focusing clients
hc keybind $mod-h	focus left
hc keybind $mod-j	focus down
hc keybind $mod-k	focus up
hc keybind $mod-l	focus right

# moving clients in tiling and floating mode
hc keybind $mod-Shift-h	shift left
hc keybind $mod-Shift-j	shift down
hc keybind $mod-Shift-k	shift up
hc keybind $mod-Shift-l	shift right

# moving the mouse
hc keybind $mod-Left 	spawn xdotool mousemove_relative --sync -- -10 0
hc keybind $mod-Down 	spawn xdotool mousemove_relative --sync 0 10
hc keybind $mod-Up 		spawn xdotool mousemove_relative --sync 0 -10
hc keybind $mod-Right 	spawn xdotool mousemove_relative --sync 10 0

# moving the mouse fast
hc keybind $mod-Shift-Left 	spawn xdotool mousemove_relative --sync -- -40 0
hc keybind $mod-Shift-Down 	spawn xdotool mousemove_relative --sync 0 40
hc keybind $mod-Shift-Up 	spawn xdotool mousemove_relative --sync 0 -40
hc keybind $mod-Shift-Right spawn xdotool mousemove_relative --sync 40 0

# clicking the mouse
hc keybind $mod-End 	spawn xdotool click 1

# splitting frames
hc keybind $mod-v       		split bottom  0.5
hc keybind $mod-c       		split right   0.5
hc keybind $mod-Control-space 	split explode

# resizing frames and floating clients
hc keybind $mod-Control-h    resize left +$resizestep
hc keybind $mod-Control-j    resize down +$resizestep
hc keybind $mod-Control-k    resize up +$resizestep
hc keybind $mod-Control-l    resize right +$resizestep

# tags (virtual desktops)
hc set default_frame_layout grid

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
	echo "${tag_names[$i]}"
    echo "${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$mod-$key" use_index "$i"
        hc keybind "$mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $mod-period use_index +1 --skip-visible
hc keybind $mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $mod-r remove
hc keybind $mod-s floating toggle
hc keybind $mod-f fullscreen toggle
hc keybind $mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $mod-Shift-m set_attr clients.focus.minimized true
hc keybind $mod-Control-m jumpto last-minimized
# hc keybind $mod-p pseudotile toggle

# cycle through layouts that affect window positioning
hc keybind $mod-space                                                   \
	or , and . compare tags.focus.curframe_wcount = 2                   \
			 . cycle_layout +1 vertical horizontal max vertical grid    \
	   , cycle_layout +1

# focus
hc keybind $mod-BackSpace   cycle_monitor
hc keybind $mod-Tab         cycle_all +1
hc keybind $mod-Shift-Tab   cycle_all -1
# hc keybind $mod-c cycle
hc keybind $mod-i jumpto urgent


# ┌────────────────┐
# │ mouse behavior │
# └────────────────┘
hc mouseunbind --all

hc mousebind $mod-Button1 move
hc mousebind $mod-Button2 zoom
hc mousebind $mod-Button3 resize


# ┌────────────┐
# │ aesthetics │
# └────────────┘
border_width=0

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color 	$(xgetres herbstluftwm.blue)
hc set frame_border_normal_color 	$(xgetres herbstluftwm.black)
hc set frame_bg_active_color 		$(xgetres herbstluftwm.blue)
hc set frame_bg_normal_color 		$(xgetres herbstluftwm.black)
hc set always_show_frame on
hc set frame_bg_transparent on
hc set frame_transparent_width 5
hc set frame_gap $((10 - border_width))
hc set frame_border_width 0

hc attr theme.title_font 			'FiraCode:pixelsize=20'
hc attr theme.inner_width 			$border_width
hc attr theme.border_width 			$border_width
hc attr theme.title_color 			$(xgetres herbstluftwm.white)
hc attr theme.active.color 			'#00000000'
hc attr theme.normal.color 			'#00000000'
hc attr theme.urgent.color 			'#00000000'
hc attr theme.normal.title_color 	$(xgetres herbstluftwm.white)
hc attr theme.active.inner_color 	$(xgetres herbstluftwm.blue)
hc attr theme.urgent.inner_color 	$(xgetres herbstluftwm.black)
hc attr theme.normal.inner_color 	'#00000000'
hc attr theme.floating.border_width 5
hc attr theme.floating.outer_width  0
hc attr theme.floating.inner_width 	0
hc attr theme.floating.border_color	transparent
hc attr theme.floating.outer_color 	$(xgetres herbstluftwm.blue)
hc attr theme.floating.inner_color 	$(xgetres herbstluftwm.blue)

# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.active.inner_width 	5
hc attr theme.background_color 		'#00000000'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings off
hc set mouse_recenter_gap 0


# ┌───────────┐
# │ rule sets │
# └───────────┘
hc unrule -F

#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# Make sure displays are configured correctly and that herbstluftwm will detect
# them properly
hc set auto_detect_monitors on
autorandr --change

# ┌──────────────┐
# │ finalization │
# └──────────────┘
~/.config/herbstluftwm/scripts/setbackground.sh --restore
hc unlock

# allow graphical-session.target to work
systemctl --user start herbstluftwm.target
